title: Phenotonic                                 # Name of the site

author:
  name: Alec Lomas                      # Default author name
  email: 'alec@phenotonic.com'                   # Default author email

taxonomies: [category,tag]                  # Arbitrary list of taxonomy types

metadata:
  description: 'Phenotonic provides the tools, expertise, and education for gardens of all varieties & gardeners of all skill levels.'               # Site description

summary:
  enabled: true                             # enable or disable summary of page
  format: short                             # long = summary delimiter will be ignored; short = use the first occurrence of delimiter or size
  size: 300                                 # Maximum length of summary (characters)
  delimiter: ===                            # The summary delimiter

redirects:
  /redirect-test: /                         # Redirect test goes to home page
  /old/(.*): /new/$1                        # Would redirect /old/my-page to /new/my-page

routes:
  /something/else: '/blog/sample-3'         # Alias for /blog/sample-3
  /new/(.*): '/blog/$1'                     # Regex any /new/my-page URL to /blog/my-page Route

blog:
  route: '/blog'                            # Custom value added (accessible via system.blog.route)

#menu:                                      # Sample Menu Example
#    - text: Source
#      icon: github
#      url: https://github.com/getgrav/grav
#    - icon: twitter
#      url: http://twitter.com/getgrav
